# location for the data
download_path: /home/rw123603/Masterarbeit/data/DOP
# location of snapshot and tensorbaord summary events (Should already exist)
save_dir: /home/rw123603/Masterarbeit/hed-tensorflow/hed
# location where to put the generated edgemaps during testing (Should already exist)
test_output: /home/rw123603/Masterarbeit/data/DOP/test_edge_maps
# parameters from the paper
model_weights_path: /home/rw123603/Masterarbeit/vgg16.npy
# training batch size, decide with your GPU size
batch_size_train: 10
# validation batch size, ran every val_interval
batch_size_val: 10
# split 30k training images for trainig/validation
train_split: 0.8
# maximum iterations to run epoc == 30k/batch_size
max_iterations: 10000
# optimizer params (not used currently Adam is used by default)
optimizer: 'adam'
optimizer_params:
    learning_rate: 0.001
    weight_decay: 0.0002
# Section 4.1 Loss for layer fusion
loss_weights: 1.0
# save snapshot every save_interval iterations
save_interval: 100
# validate on held out dataset
val_interval: 10
# learning rate decay (Not used with Adam currently)
learning_rate_decay: 0.1
# Apply weighted_cross_entropy_loss to outputs from each side layer
# Setting to false only loss after last conv layer is computed
deep_supervision: True
# Targets are continous if True else binary {0, 1}
target_regression: True
# Mean pixel value to subtract from BGR image
# just the 10 training pictures
# mean_pixel_value: [103.939, 116.779, 123.68]
# all pictures provided
mean_pixel_value: [93.237, 102.082, 94.204]
# RGB to BGR (VGG-16 trained with BGR blame OpenCV)
channel_swap: [2, 1, 0]
# training/validation data
training:
    dir: train
    list: train/train.txt
    #
    image_width: 480
    image_height: 480
    n_channels: 4
# testing data
testing:
    dir: test
    list: test/test.txt
    #
    image_width: 480
    image_height: 480
    n_channels: 4
# use snapshot after test_snapshot intervals for testing
test_snapshot: 4000
# Apply testing_threshold after sigmoid to generate binary maps set to 0.0 for continous valued edge maps
testing_threshold: 0.0
